version: '2'
services:
  app:
    image: devilbox/php-fpm:5.5-base
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
